import json
import uuid
from .database import execute_many, execute_query

# 杭州西湖/湖滨区域样例 POI 数据
HANGZHOU_POIS = [
    # 咖啡店
    {
        "name": "福叁咖啡(西湖店)",
        "city": "杭州",
        "address": "杭州市上城区湖滨路23号",
        "lng": 120.1612,
        "lat": 30.2491,
        "category": "咖啡",
        "tags": ["咖啡", "西湖", "安静", "适合拍照"],
        "rating": 4.6,
        "avg_cost": 45,
    },
    {
        "name": "%Arabica(湖滨银泰店)",
        "city": "杭州",
        "address": "杭州市上城区东坡路7号湖滨银泰in77A区",
        "lng": 120.1634,
        "lat": 30.2502,
        "category": "咖啡",
        "tags": ["咖啡", "网红", "排队", "拍照"],
        "rating": 4.4,
        "avg_cost": 40,
    },
    {
        "name": "星巴克臻选(湖滨店)",
        "city": "杭州",
        "address": "杭州市上城区湖滨路51号",
        "lng": 120.1618,
        "lat": 30.2485,
        "category": "咖啡",
        "tags": ["咖啡", "连锁", "稳定"],
        "rating": 4.3,
        "avg_cost": 38,
    },
    # 餐厅
    {
        "name": "楼外楼(孤山店)",
        "city": "杭州",
        "address": "杭州市西湖区孤山路30号",
        "lng": 120.1487,
        "lat": 30.2512,
        "category": "餐厅",
        "tags": ["杭帮菜", "老字号", "西湖醋鱼", "排队"],
        "rating": 4.2,
        "avg_cost": 120,
    },
    {
        "name": "知味观·味庄(杨公堤店)",
        "city": "杭州",
        "address": "杭州市西湖区杨公堤10-12号",
        "lng": 120.1398,
        "lat": 30.2456,
        "category": "餐厅",
        "tags": ["杭帮菜", "环境好", "适合约会", "景观位"],
        "rating": 4.5,
        "avg_cost": 150,
    },
    {
        "name": "外婆家(湖滨店)",
        "city": "杭州",
        "address": "杭州市上城区湖滨路53号",
        "lng": 120.1621,
        "lat": 30.2488,
        "category": "餐厅",
        "tags": ["杭帮菜", "性价比高", "排队"],
        "rating": 4.1,
        "avg_cost": 65,
    },
    {
        "name": "新白鹿(龙翔桥店)",
        "city": "杭州",
        "address": "杭州市上城区东坡路9号",
        "lng": 120.1630,
        "lat": 30.2498,
        "category": "餐厅",
        "tags": ["杭帮菜", "平价", "本地人推荐"],
        "rating": 4.3,
        "avg_cost": 55,
    },
    # 景点
    {
        "name": "断桥残雪",
        "city": "杭州",
        "address": "杭州市西湖区北山街",
        "lng": 120.1545,
        "lat": 30.2592,
        "category": "景点",
        "tags": ["西湖十景", "免费", "拍照", "人多"],
        "rating": 4.7,
        "avg_cost": 0,
    },
    {
        "name": "雷峰塔",
        "city": "杭州",
        "address": "杭州市西湖区南山路15号",
        "lng": 120.1498,
        "lat": 30.2389,
        "category": "景点",
        "tags": ["西湖十景", "登塔", "俯瞰西湖"],
        "rating": 4.4,
        "avg_cost": 40,
    },
    {
        "name": "三潭印月",
        "city": "杭州",
        "address": "杭州市西湖区西湖中心",
        "lng": 120.1456,
        "lat": 30.2445,
        "category": "景点",
        "tags": ["西湖十景", "坐船", "必去"],
        "rating": 4.6,
        "avg_cost": 55,
    },
    {
        "name": "苏堤",
        "city": "杭州",
        "address": "杭州市西湖区",
        "lng": 120.1423,
        "lat": 30.2478,
        "category": "景点",
        "tags": ["西湖十景", "散步", "免费", "浪漫"],
        "rating": 4.8,
        "avg_cost": 0,
    },
    {
        "name": "花港观鱼",
        "city": "杭州",
        "address": "杭州市西湖区杨公堤",
        "lng": 120.1389,
        "lat": 30.2412,
        "category": "景点",
        "tags": ["西湖十景", "免费", "亲子", "喂鱼"],
        "rating": 4.5,
        "avg_cost": 0,
    },
    # 展览/博物馆
    {
        "name": "浙江省博物馆(孤山馆区)",
        "city": "杭州",
        "address": "杭州市西湖区孤山路25号",
        "lng": 120.1482,
        "lat": 30.2518,
        "category": "展览",
        "tags": ["博物馆", "免费", "看展", "文化"],
        "rating": 4.5,
        "avg_cost": 0,
    },
    {
        "name": "中国美术学院美术馆",
        "city": "杭州",
        "address": "杭州市上城区南山路218号",
        "lng": 120.1545,
        "lat": 30.2412,
        "category": "展览",
        "tags": ["美术馆", "看展", "拍照", "艺术"],
        "rating": 4.4,
        "avg_cost": 20,
    },
    {
        "name": "西湖博物馆",
        "city": "杭州",
        "address": "杭州市上城区南山路89号",
        "lng": 120.1567,
        "lat": 30.2435,
        "category": "展览",
        "tags": ["博物馆", "免费", "了解西湖"],
        "rating": 4.3,
        "avg_cost": 0,
    },
    # 甜品/小吃
    {
        "name": "知味观(总店)",
        "city": "杭州",
        "address": "杭州市上城区仁和路83号",
        "lng": 120.1645,
        "lat": 30.2512,
        "category": "甜品",
        "tags": ["小吃", "老字号", "猫耳朵", "片儿川"],
        "rating": 4.2,
        "avg_cost": 30,
    },
    {
        "name": "弄堂里(湖滨店)",
        "city": "杭州",
        "address": "杭州市上城区东坡路",
        "lng": 120.1632,
        "lat": 30.2505,
        "category": "甜品",
        "tags": ["甜品", "下午茶", "环境好"],
        "rating": 4.3,
        "avg_cost": 50,
    },
    # 公园/休闲
    {
        "name": "太子湾公园",
        "city": "杭州",
        "address": "杭州市西湖区南山路1-1号",
        "lng": 120.1412,
        "lat": 30.2389,
        "category": "公园",
        "tags": ["公园", "免费", "赏花", "野餐"],
        "rating": 4.6,
        "avg_cost": 0,
    },
    {
        "name": "柳浪闻莺",
        "city": "杭州",
        "address": "杭州市上城区南山路",
        "lng": 120.1578,
        "lat": 30.2401,
        "category": "公园",
        "tags": ["西湖十景", "公园", "免费", "散步"],
        "rating": 4.5,
        "avg_cost": 0,
    },
    # 购物
    {
        "name": "湖滨银泰in77",
        "city": "杭州",
        "address": "杭州市上城区东坡路7号",
        "lng": 120.1635,
        "lat": 30.2505,
        "category": "购物",
        "tags": ["商场", "购物", "吃饭", "逛街"],
        "rating": 4.4,
        "avg_cost": 100,
    },
    # ============ 补充 POI ============
    # 餐厅补充
    {
        "name": "绿茶餐厅(龙井路店)",
        "city": "杭州",
        "address": "杭州市西湖区龙井路83号",
        "lng": 120.1320,
        "lat": 30.2410,
        "category": "餐厅",
        "tags": ["杭帮菜", "性价比高", "绿茶烤鸡", "排队"],
        "rating": 4.3,
        "avg_cost": 70,
    },
    {
        "name": "弄堂里(西湖店)",
        "city": "杭州",
        "address": "杭州市上城区解放路158号",
        "lng": 120.1680,
        "lat": 30.2450,
        "category": "餐厅",
        "tags": ["本帮菜", "环境好", "适合约会"],
        "rating": 4.4,
        "avg_cost": 110,
    },
    {
        "name": "老头儿油爆虾(湖滨店)",
        "city": "杭州",
        "address": "杭州市上城区邮电路9号",
        "lng": 120.1645,
        "lat": 30.2495,
        "category": "餐厅",
        "tags": ["杭帮菜", "油爆虾", "老字号", "排队"],
        "rating": 4.5,
        "avg_cost": 90,
    },
    {
        "name": "山外山菜馆",
        "city": "杭州",
        "address": "杭州市西湖区玉泉路8号",
        "lng": 120.1340,
        "lat": 30.2530,
        "category": "餐厅",
        "tags": ["杭帮菜", "老字号", "鱼头", "环境好"],
        "rating": 4.2,
        "avg_cost": 100,
    },
    {
        "name": "朴墅餐厅(青芝坞店)",
        "city": "杭州",
        "address": "杭州市西湖区青芝坞62号",
        "lng": 120.1290,
        "lat": 30.2560,
        "category": "餐厅",
        "tags": ["创意菜", "文艺", "安静", "适合约会"],
        "rating": 4.6,
        "avg_cost": 130,
    },
    # 咖啡补充
    {
        "name": "Manner Coffee(湖滨店)",
        "city": "杭州",
        "address": "杭州市上城区湖滨路步行街",
        "lng": 120.1625,
        "lat": 30.2490,
        "category": "咖啡",
        "tags": ["咖啡", "平价", "精品"],
        "rating": 4.5,
        "avg_cost": 20,
    },
    {
        "name": "Seesaw Coffee(嘉里中心店)",
        "city": "杭州",
        "address": "杭州市下城区延安路385号嘉里中心",
        "lng": 120.1690,
        "lat": 30.2620,
        "category": "咖啡",
        "tags": ["咖啡", "精品", "安静", "办公"],
        "rating": 4.4,
        "avg_cost": 38,
    },
    {
        "name": "COSTA COFFEE(西湖店)",
        "city": "杭州",
        "address": "杭州市上城区湖滨路27号",
        "lng": 120.1610,
        "lat": 30.2488,
        "category": "咖啡",
        "tags": ["咖啡", "连锁", "西湖边"],
        "rating": 4.2,
        "avg_cost": 35,
    },
    # 景点补充
    {
        "name": "灵隐寺",
        "city": "杭州",
        "address": "杭州市西湖区法云弄1号",
        "lng": 120.1180,
        "lat": 30.2580,
        "category": "景点",
        "tags": ["寺庙", "祈福", "历史", "必去"],
        "rating": 4.6,
        "avg_cost": 75,
    },
    {
        "name": "西溪湿地",
        "city": "杭州",
        "address": "杭州市西湖区天目山路518号",
        "lng": 120.0680,
        "lat": 30.2620,
        "category": "景点",
        "tags": ["湿地", "自然", "坐船", "亲子"],
        "rating": 4.5,
        "avg_cost": 80,
    },
    {
        "name": "龙井村",
        "city": "杭州",
        "address": "杭州市西湖区龙井村",
        "lng": 120.1150,
        "lat": 30.2350,
        "category": "景点",
        "tags": ["茶园", "徒步", "自然", "品茶"],
        "rating": 4.7,
        "avg_cost": 0,
    },
    {
        "name": "河坊街",
        "city": "杭州",
        "address": "杭州市上城区河坊街",
        "lng": 120.1700,
        "lat": 30.2440,
        "category": "景点",
        "tags": ["古街", "小吃", "购物", "夜景"],
        "rating": 4.1,
        "avg_cost": 50,
    },
    {
        "name": "钱塘江大桥",
        "city": "杭州",
        "address": "杭州市西湖区之江路",
        "lng": 120.1450,
        "lat": 30.2150,
        "category": "景点",
        "tags": ["地标", "拍照", "免费", "夜景"],
        "rating": 4.3,
        "avg_cost": 0,
    },
    # 展览补充
    {
        "name": "浙江美术馆",
        "city": "杭州",
        "address": "杭州市上城区南山路138号",
        "lng": 120.1550,
        "lat": 30.2380,
        "category": "展览",
        "tags": ["美术馆", "看展", "免费", "艺术"],
        "rating": 4.6,
        "avg_cost": 0,
    },
    {
        "name": "杭州博物馆",
        "city": "杭州",
        "address": "杭州市上城区粮道山18号",
        "lng": 120.1680,
        "lat": 30.2430,
        "category": "展览",
        "tags": ["博物馆", "免费", "历史", "文化"],
        "rating": 4.4,
        "avg_cost": 0,
    },
    {
        "name": "中国丝绸博物馆",
        "city": "杭州",
        "address": "杭州市上城区玉皇山路73-1号",
        "lng": 120.1520,
        "lat": 30.2370,
        "category": "展览",
        "tags": ["博物馆", "免费", "丝绸", "文化"],
        "rating": 4.5,
        "avg_cost": 0,
    },
    # 公园补充
    {
        "name": "曲院风荷",
        "city": "杭州",
        "address": "杭州市西湖区北山街89号",
        "lng": 120.1400,
        "lat": 30.2540,
        "category": "公园",
        "tags": ["西湖十景", "荷花", "免费", "散步"],
        "rating": 4.6,
        "avg_cost": 0,
    },
    {
        "name": "平湖秋月",
        "city": "杭州",
        "address": "杭州市西湖区孤山后山路",
        "lng": 120.1470,
        "lat": 30.2550,
        "category": "公园",
        "tags": ["西湖十景", "免费", "赏月", "浪漫"],
        "rating": 4.5,
        "avg_cost": 0,
    },
    {
        "name": "植物园",
        "city": "杭州",
        "address": "杭州市西湖区桃源岭1号",
        "lng": 120.1280,
        "lat": 30.2570,
        "category": "公园",
        "tags": ["公园", "植物", "亲子", "散步"],
        "rating": 4.4,
        "avg_cost": 10,
    },
    # 购物补充
    {
        "name": "解百新元华",
        "city": "杭州",
        "address": "杭州市上城区解放路251号",
        "lng": 120.1690,
        "lat": 30.2460,
        "category": "购物",
        "tags": ["商场", "购物", "老牌"],
        "rating": 4.2,
        "avg_cost": 80,
    },
    {
        "name": "杭州大厦",
        "city": "杭州",
        "address": "杭州市下城区武林广场1号",
        "lng": 120.1720,
        "lat": 30.2700,
        "category": "购物",
        "tags": ["商场", "高端", "购物"],
        "rating": 4.5,
        "avg_cost": 200,
    },
    {
        "name": "南宋御街",
        "city": "杭州",
        "address": "杭州市上城区中山中路",
        "lng": 120.1710,
        "lat": 30.2470,
        "category": "购物",
        "tags": ["古街", "文创", "拍照", "逛街"],
        "rating": 4.3,
        "avg_cost": 60,
    },
    # 甜品/小吃补充
    {
        "name": "方老大面馆",
        "city": "杭州",
        "address": "杭州市上城区邮电路46-3号",
        "lng": 120.1650,
        "lat": 30.2492,
        "category": "甜品",
        "tags": ["面馆", "本地人推荐", "平价"],
        "rating": 4.4,
        "avg_cost": 20,
    },
    {
        "name": "甘其食(龙翔桥店)",
        "city": "杭州",
        "address": "杭州市上城区延安路292号",
        "lng": 120.1640,
        "lat": 30.2520,
        "category": "甜品",
        "tags": ["包子", "早餐", "平价", "本地品牌"],
        "rating": 4.2,
        "avg_cost": 15,
    },
    {
        "name": "游埠豆浆(湖滨店)",
        "city": "杭州",
        "address": "杭州市上城区东坡路",
        "lng": 120.1635,
        "lat": 30.2500,
        "category": "甜品",
        "tags": ["早餐", "豆浆", "油条", "平价"],
        "rating": 4.3,
        "avg_cost": 12,
    },
    # 酒吧/夜景
    {
        "name": "西湖天地",
        "city": "杭州",
        "address": "杭州市上城区南山路147号",
        "lng": 120.1580,
        "lat": 30.2420,
        "category": "夜景",
        "tags": ["酒吧", "夜景", "西湖边", "氛围好"],
        "rating": 4.3,
        "avg_cost": 80,
    },
    {
        "name": "初壹酒吧",
        "city": "杭州",
        "address": "杭州市上城区南山路210号",
        "lng": 120.1560,
        "lat": 30.2405,
        "category": "夜景",
        "tags": ["酒吧", "鸡尾酒", "安静", "约会"],
        "rating": 4.5,
        "avg_cost": 90,
    },
    {
        "name": "城隍阁",
        "city": "杭州",
        "address": "杭州市上城区吴山3号",
        "lng": 120.1720,
        "lat": 30.2410,
        "category": "夜景",
        "tags": ["夜景", "登高", "俯瞰", "拍照"],
        "rating": 4.4,
        "avg_cost": 30,
    },
]


def seed_pois():
    """导入样例 POI 数据"""
    existing = execute_query("SELECT COUNT(*) as cnt FROM poi")
    if existing and existing[0]["cnt"] > 0:
        print(f"POI 表已有 {existing[0]['cnt']} 条数据，跳过导入")
        return

    sql = """
    INSERT INTO poi (id, source, source_id, name, city, adcode, address, lng, lat, category, tags, rating, avg_cost)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """

    params_list = []
    for poi in HANGZHOU_POIS:
        poi_id = f"poi_{uuid.uuid4().hex[:8]}"
        params_list.append((
            poi_id,
            "manual",
            None,
            poi["name"],
            poi["city"],
            "330100",  # 杭州 adcode
            poi["address"],
            poi["lng"],
            poi["lat"],
            poi["category"],
            json.dumps(poi["tags"], ensure_ascii=False),
            poi["rating"],
            poi["avg_cost"],
        ))

    execute_many(sql, params_list)
    print(f"成功导入 {len(params_list)} 条 POI 数据")


if __name__ == "__main__":
    from database import init_db
    init_db()
    seed_pois()
